feat: メッセージを適切に(ユーザー名、メールアドレス)
yamamoto99/es-writer pull request #53
Opened 2024-07-29 06:20 UTC by Yutosaki

## Issue

close #30 
## 処理概要

* サインアップの失敗時に、メールアドレスが既に登録されているのか、ユーザー名が既に登録されているのかのエラーメッセージをそれぞれ出す。

## 要件・仕様

* ユーザー名は`infrastructre.go`のファイルの中の`Sign Up`のとこで処理。Cognitoでそもそもユーザー名被ったらだめなようになってるからそこでエラーが返されるから、わざわざ別関数作らなかった
## 特記 / 特にレビューしてほしい箇所
* それぞれのケースで動かしてほし

## 動作確認

* サインアップの時の動作しか作ってないので、もしサインインの処理で必要な物あったら教えてください。
* 自分のとこだとサインアップのやつは両方動いた。

## パフォーマンス影響

## 参考資料

2024-07-29 10:45 UTC, muhi111 reviewed
auth usecaseのIsAlreadyRegisteredEmailは使ってないみたいだけど、大丈夫？
もしそれがいらんなら、auth repositoryのFindByEmailもいらないよ～な

2024-07-29 11:04 UTC, Yutosaki commented
すません。auth_repositoryやらuser_repositoryやらhogehoge_usecaseやらでどこが繋がってんのかよくわからんままコード書いてたせいっす。

2024-07-29 11:28 UTC, muhi111 commented on backend/main.go
> +	authController := controller.NewAuthController(authUsecase, userRepository)
おれもクリーンアーキテクチャよくわかんないんだけど、[参考したらしいレポジトリのreadme](https://github.com/GomaGoma676/echo-rest-api)を見る限り、この部分は、
```go
authController := controller.NewAuthController(authUsecase, userUsecase)
```
ってして、user usecaseも変えるほうがいいんじゃないかなぁ

2024-07-31 05:24 UTC, yamamoto99 commented on backend/main.go
> +	authController := controller.NewAuthController(authUsecase, userRepository)
- クリーンアーキテクチャは一階層に一責任が原則のはずだから`controller`から`usecase`と`repository`両方にアクセスすると、データアクセスとロジック両方の責任が入ってきてしまう
- `controller`はリクエストを受け取ってどのように処理するかまで決定して`usecase層`で具体的な処理をする。アプリケーション外部と接続する必要があるとき、`usecase層`を出て`repository層`で行う（このアプリケーションの場合DBへの接続）
- ハンドラのグループごとにファイル名を分けてるからこの場合、`userRepository`ではなく`authRepository`で検索するのがいいかも

https://zenn.dev/sre_holdings/articles/a57f088e9ca07d

2024-08-03 14:30 UTC, yamamoto99 requested changes
## 修正したほうが良いと感じた点
- クリーンアーキテクチャはcontorollerからrepositoryの関数を呼び出すことは推奨されていない
- `IsAlreadyRegisteredEmail`関数で全てのデータを取得しているが、emailのみで良いのではないか
- 変数aeって分かりにくくね？

## 詳細

> クリーンアーキテクチャはcontorollerからrepositoryの関数を呼び出すことは推奨されていない

- controllers層で取得した値をusecase層に渡して必要ならrepository層でDBにアクセスするこれが一般的な流れ
- クリーンアーキテクチャにおいてアプリケーションロジックはusecase層に書くべき
- つまり、emailが存在するかの確認はusecase層で行うべきで、controllers層で行うべきではないと思う
- controllerでemail取得→usecase→repositoryでemail検索→usecaseに戻ってemail確認→controllerに戻す

> `IsAlreadyRegisteredEmail`関数で全てのデータを取得しているが、emailのみで良いのではないか

- controllerでどうせbool型で返すので、model.usersを全て取得しなくてもemailだけ取得で良いと思う。

> 変数aeって分かりにくくね？

- aeってなんの略なん？(単純な疑問)

2024-08-04 11:20 UTC, Yutosaki commented
`controller`から`usecase`を介してrepositoryにアクセスした
`email`だけ検索した
`ae`は`authentification error`のつもりだった

2024-08-04 16:04 UTC, yamamoto99 commented
> `controller`から`usecase`を介して`repository`にアクセスしてDBを操作 `email`だけ検索した `ae`は`authentification error`のつもりだった

@Yutosaki 了解🫡
- auth_controllerの26行目消し忘れあるので抹消たのんます
- emailだけ検索する場合、結果を格納するのは`model.User`じゃなくてstringでいい気がする
```go
type User struct {
	UserID     string    `json:"id" gorm:"gorm:unique not null"`
	Username   string    `json:"username" gorm:"unique not null"`
	Email      string    `json:"email"`
	Bio        string    `json:"bio"`
	Experience string    `json:"experience"`
	Projects   string    `json:"projects"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
```
`signUpUser`でサインアップ用のユーザー情報渡してるから
```go
userRes, err := ac.authUsecase.SignUp(c, signUpUser)
```
ここで新しく関数定義しなくても
```go
func (u *authUsecase) IsAlreadyRegisteredEmail(c echo.Context, email string) (bool, error) {
    user, err := u.authRepo.FindByEmail(c, email)
    if err != nil {
        return false, err
    }
    return user.Email != "", nil
}
```
ここの中に書いちゃっていいじゃない？
```go
func (au *authUsecase) SignUp(c echo.Context, signUpUser model.SignUpUser) (model.User, error) {
	// FindByEmail

	user, err := au.infrastructure.SignUp(c, signUpUser)
	if err != nil {
		return model.User{}, err
	}

	if err := au.authRepo.CreateUser(c, user); err != nil {
		return model.User{}, err
	}

	return user, nil
}
```
↓サインアップ用の構造体(SignUpUser構造体)
```go
type SignUpUser struct {
	Username  string    `json:"username" validate:"required"`
	Email     string    `json:"email" validate:"required,email"`
	Password  string    `json:"password" validate:"required"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
```

すごくどーでも良いけど`go fmt`使うと簡単にコード整形してくれるからオヌヌメ

2024-08-04 16:07 UTC, yamamoto99 requested changes
> `controller`から`usecase`を介して`repository`にアクセスしてDBを操作 `email`だけ検索した `ae`は`authentification error`のつもりだった

@Yutosaki 了解🫡
- auth_controllerの26行目消し忘れあるので抹消たのんます
- emailだけ検索する場合、結果を格納するのは`model.User`じゃなくてstringでいい気がする
```go
type User struct {
	UserID     string    `json:"id" gorm:"gorm:unique not null"`
	Username   string    `json:"username" gorm:"unique not null"`
	Email      string    `json:"email"`
	Bio        string    `json:"bio"`
	Experience string    `json:"experience"`
	Projects   string    `json:"projects"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
```
`signUpUser`でサインアップ用のユーザー情報渡してるから
```go
userRes, err := ac.authUsecase.SignUp(c, signUpUser)
```
ここで新しく関数定義しなくても
```go
func (u *authUsecase) IsAlreadyRegisteredEmail(c echo.Context, email string) (bool, error) {
    user, err := u.authRepo.FindByEmail(c, email)
    if err != nil {
        return false, err
    }
    return user.Email != "", nil
}
```
ここの中に書いちゃっていいじゃない？
```go
func (au *authUsecase) SignUp(c echo.Context, signUpUser model.SignUpUser) (model.User, error) {
	// FindByEmail

	user, err := au.infrastructure.SignUp(c, signUpUser)
	if err != nil {
		return model.User{}, err
	}

	if err := au.authRepo.CreateUser(c, user); err != nil {
		return model.User{}, err
	}

	return user, nil
}
```
↓サインアップ用の構造体(SignUpUser構造体)
```go
type SignUpUser struct {
	Username  string    `json:"username" validate:"required"`
	Email     string    `json:"email" validate:"required,email"`
	Password  string    `json:"password" validate:"required"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
```

すごくどーでも良いけど`go fmt`使うと簡単にコード整形してくれるからオヌヌメ

2024-08-05 04:02 UTC, Yutosaki commented
* auth_controllerの26行目消し忘れあるので抹消たのんます -> done
* emailだけ検索する場合、結果を格納するのはmodel.Userじゃなくてstringでいい気がする -> done
* ここの中に書いちゃっていいじゃない？ -> 単一責任の原則的に分けた方が良いかなって感じ (正しいのかは知らん)
* すごくどーでも良いけどgo fmt使うと簡単にコード整形してくれるからオヌヌメ -> とてもやり忘れていた

2024-08-05 07:53 UTC, Yutosaki commented
`Back`ボタン追加したけど、色気に入らなかったら変えて

2024-08-05 12:49 UTC, yamamoto99 approved these changes
単一責任に関して、自分は各層で依存先は1つって解釈だったが、わからんLGTM
![image](https://github.com/user-attachments/assets/4a126d78-93ce-4ab4-abcc-fa56b63f7016)

[feat: verification code の画面にBackボタンを追加](https://github.com/yamamoto99/es-writer/pull/53/commits/25ffd838b7aac61db5659269722e574857f91ad5)
非常に欲しいと思っていたので大感謝です

2024-08-05 12:51 UTC, merged