Update profile form fields
yamamoto99/es-writer pull request #62
Opened 2024-09-25 15:16 UTC by yamamoto99

## Issue
- close #54 
## 処理概要
- Userモデルの内容を変更しフロント側も変更
## 要件・仕様
- 今までが自己PR、経験、開発経験だった箇所を経験、スキル、自己PR、キャリアプランに変更
## 動作確認
- User登録から経歴入力まで動作確認済

2024-09-26 06:30 UTC, Yutosaki requested changes
なんか入力するところの文字小さくて見づらい気がしなくもないから変えてもええかも？知らんけど

2024-09-26 06:30 UTC, Yutosaki commented on backend/model/user.go
> +	SelfPR        string     `json:"selfPR"`
空白変じゃね

2024-10-08 02:49 UTC, yamamoto99 commented
> 空白変じゃね

失礼、修正しました。

> なんか入力するところの文字小さくて見づらい気がしなくもないから変えてもええかも？知らんけど

特に何もいじってない
Webアプリにするなら現行の画面はいらなくなるから良いかなと

2024-10-08 02:52 UTC, Yutosaki approved these changes
LGTM!

2024-10-08 02:52 UTC, merged